### ISSUE TITLE
用token你注解能自动识别里面的权限标识符吗

### ISSUE THREAD

**Issue by java-aodeng** [eacdy/light-security#2]

**Comment by eacdy** [comment]
header得传 `Authorization: Bearer {你的token}` 这种形式。
参考示例有测试用例，可以玩一把看看：<https://github.com/eacdy/light-security/tree/master/light-security-example>

**相关标准详见**：<https://tools.ietf.org/html/rfc6750> ，这个文档也可以看下：<https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Authentication>

**暂不支持自定义header名**，例如：`X-Token: {你的token}`
