### ISSUE TITLE
基于代码配置

### ISSUE THREAD

**Issue by pzs-pzs** [eacdy/light-security#3]
https://github.com/eacdy/light-security/blob/952fa9ce3d6d35ec8dd63d946d82864e052db9c8/light-security-spring-boot-starter/src/main/java/com/itmuch/lightsecurity/autoconfigure/lightsecurity/LightSecurityConfiguration.java#L57
这里是不是应该返回specList？

**Comment by eacdy** [comment]
感谢指正，已修复。
