### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by zj-dreamly** [eacdy/light-security#6]
AuthInterceptor里会拦截OPTIONS请求，项目里如果配置跨域的话，这里也需要处理，不然还是还是会报no header的异常，所以为了兼容性，我觉得不如在这里过滤下OPTIONS？

**Comment by eacdy** [comment]
跨域可以使用SpringBoot跨域header就OK了哈。
<http://www.itmuch.com/work/cors/>

**Comment by zj-dreamly** [comment]
通过访问您的博客，确实解决了我的问题，之前我项目里配置跨域的方式采用的是实现拦截器，与您项目里的授权控制拦截器一样的，执行顺序有问题，您的博客里使用了过滤器，优先级更高，所以是更好的选择，非常感谢，谢谢

**Comment by eacdy** [comment]
@zj-dreamly 不客气，哈哈^_^
